### ISSUE TITLE
Review: Comparisons to other common packages

### ISSUE THREAD

**Issue by mnarayan** [dmey/synthia#23]
What are other packages people might use to simulate data (e.g. statsmodels comes to mind) and how is this package different? Your package supports generating data for multivariate copula distributions and via fPCA. I understand what this entails but I think this could use further elaboration. 

This package supports nonparametric distributions much more than the typical parametric data generators found in common packages and it would be useful to highlight these explicitly.

**Comment by dmey** [comment]
I think have addressed this in the paper -- but please let me know if this is still unclear.
