### ISSUE TITLE
Review: Clarify API

### ISSUE THREAD

**Issue by mnarayan** [dmey/synthia#25]
It would be helpful to add/explain what the different classes do `Data Generators`, `Parametrizer`, `Transformers` somewhere in the introduction or usage component of the documentation. Explain the different classes and what each is supposed to do. If it is similar to or inspired by well-known API of a different package, please point to it. 

I think generators and transformers are obvious but I only sort of understand `Parametrizers`. It is also confusing in the sense that people might think this has something to do with parametric distributions when you mean it to be something different. 

Is this API for `Parametrizers` inspired by some convention elsewhere? If so it would be helpful to point to that. For instance, the generators are very similar to statsmodel generators.

**Comment by dmey** [comment]
Thanks for the feedback -- I have updated the API as per you comments. Can you please check https://dmey.github.io/synthia/api.html and let me know if the sections are clearer?

**Comment by mnarayan** [comment]
LGTM
