### ISSUE TITLE
Small error in docs

### ISSUE THREAD

**Issue by BigTuna08** [dmey/synthia#28]
Hi, just letting you know I noticed a small error in the documentation. 

At the bottom of this page https://dmey.github.io/synthia/examples/fpca.html

The error is in line [6] of the code, under "Plot the results".

You have:
plot_profiles(ds_true, 'temperature_fl')

But I believe it should be: 
plot_profiles(ds_synth, 'temperature_fl')
# you want to plot results, not the original here.

Cheers & thanks for the cool project!

**Comment by dmey** [comment]
Good catch! Fixed in #29. Thanks!
